# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_stat', models.CharField(max_length=10, null=True)),
                ('order_id', models.CharField(max_length=50)),
                ('order_source', models.CharField(max_length=50)),
                ('prod_name', models.CharField(max_length=50, null=True)),
                ('prod_url', models.CharField(blank=True, max_length=500, null=True)),
                ('cost_price', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
    ]
